In [1]:
import os
import sys

import numpy as np
import matplotlib.pyplot as plt
import time

sys.path.append("../")

from src.utils import *
from src.core.pybullet_core import PybulletCore

from neuromeka import IndyDCP3
from neuromeka import JointTeleopType, TaskTeleopType

indy = IndyDCP3(robot_ip='192.168.0.22', index=0)

In [2]:
def bounce(robot: IndyDCP3, current_robot_pos: np.ndarray, target_ball_pos: np.ndarray, bounce_force = 1.0):
    robot.movetelel_abs(tpos = current_robot_pos - bounce_force * np.array([0, 0, 10, 0, 0, 0]))
    time.sleep(0.05 * bounce_force)
    robot.movetelel_abs(tpos = current_robot_pos)
    time.sleep(0.05 * bounce_force)

In [ ]:
horizontal_orientation_xyz = np.array([90, 104.5, 90])
home_pos = np.array([550, -200, 500, 90, 104.5, 90]) # x, y, z (mm), x, y, z (deg)
init_jpos = indy.get_control_data()['q']
home_pos_ik = indy.inverse_kin(home_pos, init_jpos)["jpos"]
move_response = indy.movej(jtarget = home_pos_ik)
time.sleep(2)

#indy.start_teleop(method=TaskTeleopType.ABSOLUTE)
#time.sleep(3)

#pos = np.array([0, 0, 80, 0, 0, 0])
#init_jpos = indy.get_control_data()['q']
#ik = indy.inverse_kin(home_pos + pos, init_jpos)["jpos"]

vertex_points = np.array([[-200, 150, 0],
                 [-200, -150, 0],
                 [200, -150, 0],
                 [200, 150, 0]])

for translation in vertex_points:
    target_t = home_pos + np.concatenate((translation, np.zeros(3)), axis = 0)
    print(target_t)
    indy.movel(ttarget = target_t)
    time.sleep(2)

time.sleep(3)


[350. -50. 500. 180. 209. 180.]
[ 350. -350.  500.  180.  209.  180.]
[ 750. -350.  500.  180.  209.  180.]
[750. -50. 500. 180. 209. 180.]


In [4]:
indy.stop_teleop()

{'msg': 'TeleOp Stop Requested', 'code': '0'}

In [5]:
indy.recover()

{'msg': 'Success', 'code': '0'}